name: Node

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
        examples: ["html", "nuxt", "vite", "vue-cli"]

    name: examples-build
    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # TODO: Remove when min LTS is 16
      - name: Set up npm 7 for node 14
        if: matrix.node-version == '14'
        run: npm i -g npm@^7

      - name: Install dependencies and build library
        run: |
          npm ci
          npm run build --if-present
          npm pack

      - name: Install example dependencies
        working-directory: "examples/${{ matrix.examples }}"
        run: |
          npm ci
          version=$(cat ../../package.json | jq --raw-output .version)
          npm install -D ../../skjnldsv-vue-plyr-$version.tgz

      - name: Build ${{ matrix.examples }} example
        working-directory: "examples/${{ matrix.examples }}"
        run: npm run build --if-present

  summary:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    name: examples-summary
    steps:
      - name: Summary status
        run: if ${{ needs.build.result != 'success' && needs.build.result != 'skipped' }}; then exit 1; fi
